### PR TITLE
refactor plugin to use ES6 modules

### LINKED ISSUE #66: move to ES6
we need to follow in the footsteps of Esri/esri-leaflet#525

### PR DESCRIPTION
**Pull request by jgravois**
will resolve #66

### what **is** ready

* cleaned up and updated the `package.json`
* got rid of the dist folder in the readme
* took a pass at rewriting all classes using ES6
* got the build script running
* updated the debug/sample.html to load the compiled source
* confirmed that i was including `addInitHook()` correctly by testing whether a simple console.log() would fire when L.esri.FeatureLayer initialized.

### what is **not** ready

i have not figured out how to get a reference to Leaflet itself (to extend relevant classes) correctly yet.  i attempted to follow the same convention used in [Esri Leaflet](https://github.com/Esri/esri-leaflet/blob/master/scripts/build.js#L16), but in this branch i can see that references to `L` have been replaced with `L__default` in the compiled source, which, not surprisingly is `not defined`.

#### i tried several things:

1. importing specific classes from Leaflet, but the `.` is no bueno
```js
import L.Class from 'leaflet';
```
2. trying to alias the `L` global
```js
import L as foo from 'leaflet';
// ...
export var Renderer = foo.Class.extend({// ...
```
3. adding a `globals` argument when building (like i use in [gp](https://github.com/jgravois/esri-leaflet-gp/blob/master/scripts/build.js#L23-L26)) to map both `L` and an arbitrary alias
```js
var transpiled = bundle.generate({
    // ...
    moduleName: 'L.esri.GP',
    globals: {
      "leaflet": "wtf",
      "esri-leaflet": "L.esri"
    }
  });
```
different iterations (including whether or not "esri-leaflet" is mentioned as a global as well) just lead to different failures.

### CODE REVIEW

**Comment by jgravois** [comment]
cc @patrickarlt   any ideas?

**Comment by kneemer** [comment]
@jgravois I got it to the point where I can view renderers and the tests pass.  The Esri Marker symbols do not work because  https://github.com/Esri/Leaflet.ShapeMarkers needs to have an ES6 refactor as well.  Let me know if the changes work for you.

**Comment by jgravois** [comment]
awesome work!

i had the inverse problem as you when i pulled down this code.  i couldn't run semistandard until **after** i removed the `eslint` devDependency.

not sure how, but a bunch more linting errors came up too.  other than that i just pulled out the curly braces in import statements and made the dependency on leaflet explicitly `1.0.0-beta1` or above.

all is well for me.  if you can get tests passing locally with my latest changes, lets merge.

**Comment by kneemer** [comment]
The linting errors are my fault, I wasn't able to run semistandard so I committed without linting.  I had planned to resolve that before merging but you got it for me.  Thanks.

Esri shape markers are not working yet and there is not a specific test for them.  I was going to add tests and resolve the markers before merging.

**Comment by jgravois** [comment]
works for me.  let me know if I can help.

once we get all this merged into `master` I plan on making the official announcement about esri-leaflet 2.0.0-beta.1 and updating the website.

**Comment by jgravois** [comment]
i laid down two more commits that get us halfway to passing tests.

the only error left (repeated 11 times) is:

> PhantomJS 1.9.8 (Mac OS X 0.0.0) TypeError: 'undefined' is not a function (evaluating 'this.callInitHooks()')

this is happening in tests that instantiate a renderer manually. (ie:)
```js
var renderer = L.esri.Renderers.classBreaksRenderer(rendererJson);
```
stepping throw the same code in a simple app, it looks like the initialization logic in L.Class is also being called on `L.Renderers` for some reason...

might have something to do with Leaflet/Leaflet#2545 (which was resolved in 1.0.0-beta1), but i don't have a firm enough grasp on the moving parts to understand exactly what's going on.

**Comment by kneemer** [comment]
This commit gets me to passing tests, the lineSymbol constructor was upper cased and wasn't initializing.    Each of the classes has an upper case definition and then a lower case initializer so you don't have to 'new' it up.  L.Class will be called for almost all the initializers in this plugin because it is using the inheritance model of leaflet.

**Pull request merged**
