### PR TITLE
Outsource markers

### LINKED ISSUE #14: Pull markers out into separate repo/plugin
The markers could be reused by anyone wanting to use one of the Esri marker types; Square, Cross, X or Diamond.  They should get their own space and pulled into this plugin when building.

@patrickarlt do you have any opinions on naming or structure of the plugin?  esri-leaflet-markers, esri-markers?

### PR DESCRIPTION
**Pull request by kneemer**
Moved markers into a separate repository https://github.com/Esri/Leaflet.ShapeMarkers and pulled out the shared code within that repo.

Updated node dependencies to use shorthand git notation.

Resolves #14

### CODE REVIEW

**Comment by jgravois** [comment]
:+1:  very cool!

if you want, i can pull down these changes locally and confirm everything works as expected before merging.

**Comment by kneemer** [comment]
That would be great.

**Comment by jgravois** [comment]
took me a few trys to `npm install` the new dependencies, but afterwards everything looked good and all tests are passing.

**Comment by kneemer** [comment]
Once there are releases for leaflet 1.0 and the corresponding esri-leaflet, we can remove the postInstall script which was probably the reason for any issues during npm install.

**Comment by jgravois** [comment]
ahh... maybe we could chat for a few minutes on the phone sometime soon.  i'd like to get my own plugins prepped for 1.0 and i don't quite understand where the [post install script](https://github.com/Esri/esri-leaflet-renderers/blob/leaflet-1.0/package.json#L8) is actually located.

**Comment by kneemer** [comment]
Sure,  are you available late this afternoon?

**Pull request merged**
